### ISSUE TITLE
All Live Examples seems to be Broken

### ISSUE THREAD

**Issue by NicksonYap** [Nhogs/popoto-examples#16]
https://nhogs.github.io/popoto-examples/factual/index.html

It seems to have failed to load resource: https://unpkg.com/materialize-css@1.0.0-rc.2/index.js

-- Edit:

It seems all the Live Examples are Broken (only see a blue-gray page)

![image](https://user-images.githubusercontent.com/5380731/50179710-b3c0e980-0342-11e9-93fd-10e99e0107e5.png)

**Comment by Popotojs** [comment]
It looks like an issue with [unpkg](https://unpkg.com) file resolution.
https://unpkg.com/popoto is supposed to resolve to https://unpkg.com/popoto@latest/dist/popoto.min.js
using `"unpkg"` deafult parameter from package.json but it seems it's no more the case.

I'll see what I can do to improve this.

**Comment by Popotojs** [comment]
unpkg/unpkg.com/issues/156

I'm looking if I should change the dependencies references in project to avoid this kind of issue.

**Comment by NicksonYap** [comment]
Why don't we use webpack and "npm install" the package?

**Comment by Popotojs** [comment]
I want the examples to be hosted directly in [GitHub Pages](https://pages.github.com/) of the project.

As they are statics HTML and JavaScript I just had to turn on the feature on the master branch and every examples can be tested directly with its live url.
example: https://nhogs.github.io/popoto-examples/simple-graph/index.html

Using services like [unpkg](https://unpkg.com/popoto/) or [jsDelivr](https://www.jsdelivr.com/package/npm/popoto) is an easy way to always references latest version of dependencies on client side. 

One possibility would be to host dependencies in the project but trigger a new build on every new releases of a dependency. It is more complex to setup.

But you are right that I can create a NPM package of this project in order to run it locally.
Would it be useful for you?

**Comment by NicksonYap** [comment]
I think the versions of dependancies should not be updated automatically to
avoid breaking the examples

Also this will allow running fully in local host.

I think it'e just more proper & reliable to host dependacies ourselves,
especially when tools like npm & webpack is built for this

Most projects now use webpack and nom anyways so it'll be easier to
integrate

**Comment by Popotojs** [comment]
I chose the easy solution to store the dependencies dist in repo and reference them locally to avoid new version breakage. 

This solution works well on gh-pages and locally
